//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WEB02.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WEB02.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản có.
        /// </summary>
        public static string MISA_CreditAccount_Name {
            get {
                return ResourceManager.GetString("MISA_CreditAccount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản nợ.
        /// </summary>
        public static string MISA_DebitAccount_Name {
            get {
                return ResourceManager.GetString("MISA_DebitAccount_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Phòng ban.
        /// </summary>
        public static string MISA_DepartmentId_Name {
            get {
                return ResourceManager.GetString("MISA_DepartmentId_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string MISA_EmpCode_Name {
            get {
                return ResourceManager.GetString("MISA_EmpCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên nhân viên.
        /// </summary>
        public static string MISA_Fullname_Name {
            get {
                return ResourceManager.GetString("MISA_Fullname_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string MISA_GenderName_Female {
            get {
                return ResourceManager.GetString("MISA_GenderName_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string MISA_GenderName_Male {
            get {
                return ResourceManager.GetString("MISA_GenderName_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string MISA_GenderName_Other {
            get {
                return ResourceManager.GetString("MISA_GenderName_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghỉ phép.
        /// </summary>
        public static string MISA_WorkStatus_Holiday {
            get {
                return ResourceManager.GetString("MISA_WorkStatus_Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã nghỉ việc.
        /// </summary>
        public static string MISA_WorkStatus_Stop {
            get {
                return ResourceManager.GetString("MISA_WorkStatus_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang làm việc.
        /// </summary>
        public static string MISA_WorkStatus_Working {
            get {
                return ResourceManager.GetString("MISA_WorkStatus_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống đã gặp lỗi. Xin vui lòng liên hệ MISA để xử lý vấn đề này..
        /// </summary>
        public static string VN_ErrorExceptionMsg {
            get {
                return ResourceManager.GetString("VN_ErrorExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không đúng định dạng..
        /// </summary>
        public static string VN_ErrorFormatCode {
            get {
                return ResourceManager.GetString("VN_ErrorFormatCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đã tồn tại trong hệ thống, vui lòng kiểm tra lại. .
        /// </summary>
        public static string VN_ExistData {
            get {
                return ResourceManager.GetString("VN_ExistData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đã có phát sinh. Bạn phải xóa các phát sinh liên quan trước khi xóa nhà cung cấp..
        /// </summary>
        public static string VN_ExistVendorInPayment {
            get {
                return ResourceManager.GetString("VN_ExistVendorInPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phương thức không được cho phép .
        /// </summary>
        public static string VN_MethodNotAllowed {
            get {
                return ResourceManager.GetString("VN_MethodNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được để trống..
        /// </summary>
        public static string VN_NoEmpty {
            get {
                return ResourceManager.GetString("VN_NoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trường dữ liệu không được để trống.
        /// </summary>
        public static string VN_NoEmptyMsg_Common {
            get {
                return ResourceManager.GetString("VN_NoEmptyMsg_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Phòng ban không được để trống..
        /// </summary>
        public static string VN_NoEmptyMsg_DepartmentId {
            get {
                return ResourceManager.GetString("VN_NoEmptyMsg_DepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được để trống..
        /// </summary>
        public static string VN_NoEmptyMsg_EmpCode {
            get {
                return ResourceManager.GetString("VN_NoEmptyMsg_EmpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên nhân viên không được để trống..
        /// </summary>
        public static string VN_NoEmptyMsg_Fullname {
            get {
                return ResourceManager.GetString("VN_NoEmptyMsg_Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không tồn tại trong hệ thống..
        /// </summary>
        public static string VN_NotExistData {
            get {
                return ResourceManager.GetString("VN_NotExistData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ..
        /// </summary>
        public static string VN_NotValidRequest {
            get {
                return ResourceManager.GetString("VN_NotValidRequest", resourceCulture);
            }
        }
    }
}
